#include <stdint.h>

// Transparent color for sprites (white)
#define SPRITE_TRANSPARENT 0xFFFF

// Precomputed RGB565 colors (consistent with macro in lcd_ili9488.h)
// RGB565(r,g,b) = ((r&0x1F)<<11) | ((g&0x3F)<<5) | (b&0x1F)
#define COLOR_GREEN 0x07E0  // RGB565(0, 63, 0)
#define COLOR_RED   0xF800  // RGB565(31, 0, 0)
#define COLOR_BLUE  0x001F  // RGB565(0, 0, 31)
#define COLOR_BLACK 0x0000  // RGB565(0, 0, 0)

// 16x16 hero sprite (black) - diamond/rhombus shape
const uint16_t sprite_hero[16 * 16] = {
    // Row 0
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 1
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 2
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 3
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 4
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 5
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 6
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 7
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 8
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 9
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 10
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Row 11
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 12
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 13
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 14
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Row 15
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
};

// 16x16 enemy sprite (red) - checkerboard pattern
const uint16_t sprite_enemy[16 * 16] = {
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
};
