#include <stdint.h>

// Colore trasparente per gli sprite (bianco)
#define SPRITE_TRANSPARENT 0xFFFF

// Colori RGB565 precalcolati (coerenti con la macro in lcd_ili9488.h)
// RGB565(r,g,b) = ((r&0x1F)<<11) | ((g&0x3F)<<5) | (b&0x1F)
#define COLOR_GREEN 0x07E0  // RGB565(0, 63, 0)
#define COLOR_RED   0xF800  // RGB565(31, 0, 0)
#define COLOR_BLUE  0x001F  // RGB565(0, 0, 31)
#define COLOR_BLACK 0x0000  // RGB565(0, 0, 0)

// Sprite 16x16 hero (nero) - forma di rombo/diamante
const uint16_t sprite_hero[16 * 16] = {
    // Riga 0
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 1
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 2
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 3
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 4
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 5
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 6
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 7
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 8
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 9
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 10
    SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT,

    // Riga 11
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 12
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 13
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, COLOR_BLACK, COLOR_BLACK,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 14
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_BLACK, COLOR_BLACK,
    COLOR_BLACK, COLOR_BLACK, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,

    // Riga 15
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
};

// Sprite 16x16 enemy (rosso) - pattern a scacchiera
const uint16_t sprite_enemy[16 * 16] = {
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
    SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT, COLOR_RED, COLOR_RED, SPRITE_TRANSPARENT, SPRITE_TRANSPARENT,
};
